# Enable base.yml to be executed as a dispatch workflow with:
#
# gh workflow run base-wrapper.yml \
#  -f quarkus-repo=gsmet/quarkus -f quarkus-version=2.2.4-backports-1 \
#  -f builder-image="quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11"
name: Mandrel-Quarkus tests wrapper

on:
  workflow_dispatch:
    inputs:
      quarkus-version:
        type: string
        description: 'Quarkus version to test (branch, tag, commit, or "latest")'
        # "latest" is replaced by the latest release available in maven
        default: "main"
      quarkus-repo:
        type: string
        description: 'The Quarkus repository to be used'
        default: 'quarkusio/quarkus'
      repo:
        type: string
        description: 'The Mandrel/Graal repository to be used'
        default: 'graalvm/mandrel'
      version:
        type: string
        description: 'Mandrel version to test (branch, tag, or commit)'
        default: "graal/master"
      mandrel-packaging-version:
        type: string
        description: 'Mandrel packaging version to test (branch, tag, or commit)'
        default: "master"
      mandrel-packaging-repo:
        type: string
        description: 'Mandrel packaging repository to be used'
        default: "graalvm/mandrel-packaging"
      build-type:
        type: choice
        description: 'Build distribution (graal/mandrel) from source or use released binaries'
        default: "mandrel-source"
        options:
          - "mandrel-source"
          - "graal-source"
          - "mandrel-release"
          - "graal-release"
      jdk:
        type: choice
        description: 'OpenJDK to use. One of 11/ga, 11/ea, 17/ga, 17/ea (/ga and /ea suffixes are only relevant when building from source)'
        default: "11/ga"
        options:
          - "11/ga"
          - "11/ea"
          - "17/ga"
          - "17/ea"
      builder-image:
        type: string
        description: 'The builder image to use instead of a release or building from source (e.g. quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11)'
        default: "null"
      build-stats-tag:
        type: string
        description: 'The tag to use for build stats uploads of native tests (e.g. 22.3.0-dev-jdk17-prepatch-x)'
        default: "null"

jobs:
  delegate:
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: ${{ github.event.inputs.quarkus-version }}
      quarkus-repo: ${{ github.event.inputs.quarkus-repo }}
      repo: ${{ github.event.inputs.repo }}
      version: ${{ github.event.inputs.version }}
      mandrel-packaging-version: ${{ github.event.inputs.mandrel-packaging-version }}
      mandrel-packaging-repo: ${{ github.event.inputs.mandrel-packaging-repo }}
      build-type: ${{ github.event.inputs.build-type }}
      jdk: ${{ github.event.inputs.jdk }}
      builder-image: ${{ github.event.inputs.builder-image }}
      build-stats-tag: ${{ github.event.inputs.build-stats-tag }}
    secrets:
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
