name: Repo Sync

on:
  push:
    branches:
    - default
    paths:
    - .github/workflows/repo-sync.yml
  schedule:
  - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  graal-master:
    name: Keep graal/master in sync with upstream master
    runs-on: ubuntu-latest
    steps:
    - name: Checkout graal/master branch
      uses: actions/checkout@v4
      with:
        ref: graal/master
        fetch-depth: 0
    - name: Echo issue repo and number
      run: |
        echo "issue-repo: graalvm/mandrel"
        echo "issue-number: 649"
    - name: Sync branch
      run: |
        git config --local user.email "fzakkak@redhat.com"
        git config --local user.name "Foivos Zakkak through GH action"
        git remote add upstream https://github.com/oracle/graal
        git fetch upstream master
        git merge --ff-only upstream/master
        git push --quiet origin graal/master
