name: Weekly CI

on:
  push:
    paths:
      - '.github/workflows/weekly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
  pull_request:
    paths:
      - '.github/workflows/weekly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
  schedule:
    - cron: '15 0 * * 6'
  workflow_dispatch:

# The following aims to reduce CI CPU cycles by:
# 1. Cancelling any previous builds of this PR when pushing new changes to it
# 2. Cancelling any previous builds of a branch when pushing new changes to it in a fork
# 3. Cancelling any pending builds, but not active ones, when pushing to a branch in the main
#    repository. This prevents us from constantly cancelling CI runs, while being able to skip
#    intermediate builds. E.g., if we perform two pushes the first one will start a CI job and
#    the second one will add another one to the queue; if we perform a third push while the
#    first CI job is still running the previously queued CI job (for the second push) will be
#    cancelled and a new CI job will be queued for the latest (third) push.
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'graalvm/mandrel' }}

jobs:
  ####
  # Test Mandrel with JDK 22
  ####
#  q-main-mandrel-jdk-22:
#    name: "Q main M latest JDK 22"
#    uses: ./.github/workflows/base.yml
#    with:
#      quarkus-version: "main"
#      version: "graal/master"
#      jdk: "22/ea"
#      issue-number: "580"
#      issue-repo: "graalvm/mandrel"
#      mandrel-it-issue-number: "208"
#      build-stats-tag: "gha-linux-qmain-mlatest-jdk22ea"
#    secrets:
#      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
#      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
#  q-main-mandrel-jdk-22-win:
#    name: "Q main M latest JDK 22 windows"
#    uses: ./.github/workflows/base-windows.yml
#    with:
#      quarkus-version: "main"
#      version: "graal/master"
#      jdk: "22/ea"
#      issue-number: "579"
#      issue-repo: "graalvm/mandrel"
#      mandrel-it-issue-number: "207"
#      build-stats-tag: "gha-win-qmain-mlatest-jdk22ea"
#    secrets:
#      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
#      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Q main and GraalVM CE JDK 21 since Mandrel 21 builds are
  # currently not possible (#598)
  ####
  q-main-graal-21-latest:
    name: "Q main G 21 latest"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      version: "graal/master"
      build-type: "graal-source"
      jdk: "21/ea"
      build-stats-tag: "gha-linux-graal-qmain-glatest-jdk21ea"
    secrets:
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Q main and Mandrel 24.0 JDK 22 builder image
  ####
  q-main-mandrel-24_0:
    name: "Q main M 24 JDK 22"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      build-stats-tag: "gha-linux-qmain-m24_0-builder-image"
      builder-image: "quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-22"
    secrets:
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Q main and Mandrel 24.1 JDK 23
  ####
  q-main-mandrel-24_1-ea:
    name: "Q main M 24.1 JDK 23 EA"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      version: "mandrel/24.1"
      jdk: "23/ea"
      issue-number: "742"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "244"
      build-stats-tag: "gha-linux-qmain-m24_1-jdk23ea"
      mandrel-packaging-version: "24.1"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  q-main-mandrel-24_1-ea-win:
    name: "Q main M 24.1 JDK 23 EA windows"
    uses: ./.github/workflows/base-windows.yml
    with:
      quarkus-version: "main"
      version: "mandrel/24.1"
      jdk: "23/ea"
      issue-number: "743"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "243"
      build-stats-tag: "gha-win-qmain-m24_1-jdk23ea"
      mandrel-packaging-version: "24.1"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Q main and Mandrel 24.0 JDK 22
  ####
  q-main-mandrel-24_0-ea:
    name: "Q main M 24.0 JDK 22 EA"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      version: "mandrel/24.0"
      jdk: "22/ea"
      issue-number: "644"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "240"
      build-stats-tag: "gha-linux-qmain-m24_0-jdk22ea"
      mandrel-packaging-version: "24.0"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  q-main-mandrel-24_0-ea-win:
    name: "Q main M 24.0 EA windows"
    uses: ./.github/workflows/base-windows.yml
    with:
      quarkus-version: "main"
      version: "mandrel/24.0"
      jdk: "22/ea"
      issue-number: "645"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "241"
      build-stats-tag: "gha-win-qmain-m24_0-jdk22ea"
      mandrel-packaging-version: "24.0"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Q main and Mandrel 23.1 JDK 21
  ####
  q-main-mandrel-23_1:
    name: "Q main M 23.1 JDK 21"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      version: "mandrel/23.1"
      jdk: "21/ea"
      issue-number: "739"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "198"
      build-stats-tag: "gha-linux-qmain-m23_1-jdk21ea"
      mandrel-packaging-version: "23.1"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  q-main-mandrel-23_1-win:
    name: "Q main M 23.1 windows"
    uses: ./.github/workflows/base-windows.yml
    with:
      quarkus-version: "main"
      version: "mandrel/23.1"
      jdk: "21/ea"
      issue-number: "740"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "199"
      build-stats-tag: "gha-win-qmain-m23_1-jdk21ea"
      mandrel-packaging-version: "23.1"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Q main and Mandrel 23.0 JDK 17
  ####
  q-main-mandrel-23_0:
    name: "Q main M 23.0 JDK 17"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      build-type: "mandrel-source-nolocalmvn"
      version: "mandrel/23.0"
      jdk: "17/ea"
      mandrel-packaging-version: "23.0"
  ####
  # Test Quarkus 3.2 with Mandrel 23.0 JDK 17
  ####
  q-3_2-mandrel-23_0:
    name: "Q 3.2 M 23.0 JDK 17"
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "3.2"
      build-type: "mandrel-source-nolocalmvn"
      version: "mandrel/23.0"
      jdk: "17/ea"
      mandrel-packaging-version: "23.0"
